#!/bin/bash
# Project Vault — Automated Initialization Script
# Usage: bash init-vault.sh [project-path] [project-name] [phase]
# Example: bash init-vault.sh . "My App" mvp
#
# Phases: idea | prototype | mvp | growth | maintenance | sunset
# If phase is omitted, auto-detects based on project files.

set -e

PROJECT_PATH="${1:-.}"
PROJECT_NAME="${2:-$(basename "$(cd "$PROJECT_PATH" && pwd)")}"
PHASE="${3:-auto}"

cd "$PROJECT_PATH"
PROJECT_ROOT="$(pwd)"

# --- Auto-detect phase if not specified ---
if [ "$PHASE" = "auto" ]; then
  if [ -f "package.json" ] || [ -f "requirements.txt" ] || [ -f "pyproject.toml" ] || [ -f "Cargo.toml" ] || [ -f "go.mod" ]; then
    if [ -d "src" ] || [ -d "app" ] || [ -d "lib" ]; then
      PHASE="mvp"
    else
      PHASE="prototype"
    fi
  elif [ -f "*.html" ] || [ -f "index.html" ]; then
    PHASE="prototype"
  elif [ -f "README.md" ] || [ -f "项目构想.md" ]; then
    PHASE="idea"
  else
    PHASE="idea"
  fi
  echo "🔍 Auto-detected phase: $PHASE"
fi

TODAY=$(date +%Y-%m-%d)

echo ""
echo "=========================================="
echo "  Project Vault Init"
echo "=========================================="
echo "  Project:  $PROJECT_NAME"
echo "  Path:     $PROJECT_ROOT"
echo "  Phase:    $PHASE"
echo "  Date:     $TODAY"
echo "=========================================="
echo ""

# --- Create directories ---
mkdir -p docs/vault/templates
mkdir -p assets/intake/reports
echo "✅ Directories created"

# --- .gitignore handling ---
if [ ! -f ".gitignore" ]; then
  cat > .gitignore << 'GITIGNORE'
# Dependencies
node_modules/
venv/
.venv/
__pycache__/

# Environment
.env
.env.local

# IDE
.idea/
.vscode/

# OS
.DS_Store
Thumbs.db

# Build
dist/
build/
.next/

# Logs
*.log
GITIGNORE
  echo "✅ .gitignore created (was missing)"
else
  # Check if .env is in .gitignore
  if ! grep -q "^\.env" .gitignore 2>/dev/null; then
    echo "" >> .gitignore
    echo "# Environment" >> .gitignore
    echo ".env" >> .gitignore
    echo ".env.local" >> .gitignore
    echo "✅ .gitignore updated (added .env)"
  else
    echo "✅ .gitignore exists"
  fi
fi

# --- Detect sensitive patterns ---
SENSITIVE_PATTERNS=""
if [ -f ".env.example" ]; then
  SENSITIVE_PATTERNS=$(grep -oP '^[A-Z_]+=' .env.example 2>/dev/null | sed 's/=$//' | head -10 || true)
fi
if [ -f ".env" ]; then
  echo "⚠️  WARNING: .env file exists — make sure it's in .gitignore!"
fi

# --- Detect project info ---
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
COMMIT=$(git log --oneline -1 2>/dev/null || echo "no commits")
COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Detect tech stack
TECH_STACK="Unknown"
if [ -f "package.json" ]; then
  if grep -q "react" package.json 2>/dev/null; then TECH_STACK="React"
  elif grep -q "vue" package.json 2>/dev/null; then TECH_STACK="Vue"
  elif grep -q "next" package.json 2>/dev/null; then TECH_STACK="Next.js"
  else TECH_STACK="Node.js"
  fi
elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
  if grep -q "django" requirements.txt 2>/dev/null || grep -q "django" pyproject.toml 2>/dev/null; then TECH_STACK="Django"
  elif grep -q "flask" requirements.txt 2>/dev/null || grep -q "flask" pyproject.toml 2>/dev/null; then TECH_STACK="Flask"
  elif grep -q "fastapi" requirements.txt 2>/dev/null || grep -q "fastapi" pyproject.toml 2>/dev/null; then TECH_STACK="FastAPI"
  else TECH_STACK="Python"
  fi
elif [ -f "Cargo.toml" ]; then TECH_STACK="Rust"
elif [ -f "go.mod" ]; then TECH_STACK="Go"
elif [ -f "index.html" ]; then TECH_STACK="HTML/CSS/JS"
fi
echo "🔍 Detected tech stack: $TECH_STACK"

# --- Detect commands ---
COMMANDS=""
if [ -f "package.json" ]; then
  COMMANDS=$(python3 -c "
import json
with open('package.json') as f:
    d = json.load(f)
for k,v in d.get('scripts',{}).items():
    print(f'npm run {k} — {v}')
" 2>/dev/null || echo "")
fi
if [ -f "Makefile" ]; then
  COMMANDS="$COMMANDS\n$(grep '^[a-zA-Z_-]*:' Makefile 2>/dev/null | sed 's/:.*$//' | sed 's/^/make /' || true)"
fi

# --- Generate vault files ---
echo "📝 Generating vault files..."

# 00_HOME.md
cat > docs/vault/00_HOME.md << EOF
---
type: home
status: active
confidence: medium
last_updated: $TODAY
owner: both
reviewed_by: unreviewed
aliases: ["$PROJECT_NAME", "$PROJECT_NAME Home"]
---

# $PROJECT_NAME — Project Vault

> Auto-generated by Project Vault init. Customize this file.

## Quick Facts

| Key | Value |
|-----|-------|
| **Project** | $PROJECT_NAME |
| **Phase** | $PHASE |
| **Tech Stack** | $TECH_STACK |
| **Branch** | $BRANCH |
| **Last Commit** | $COMMIT_SHORT |
| **Last Updated** | $TODAY |

## Agent Entry Page

> **Every new Agent MUST read this page first.**

**Mandatory reading order:**
1. [[00_HOME]] — You are here
2. [[01_CURRENT_BASELINE]] — Source of truth
3. [[03_DO_NOT_TOUCH]] — Danger zones
4. [[05_COMMANDS_AND_FILES]] — What you can run
5. [[VAULT_SCHEMA]] — Vault rules

**After completing any task, you MUST:**
- Update [[01_CURRENT_BASELINE]] if status changed
- Append to [[VAULT_CHANGELOG]]

## Vault Navigation

- [[01_CURRENT_BASELINE]] — Current state
- [[02_DECISION_LOG]] — Key decisions
- [[03_DO_NOT_TOUCH]] — Danger zones
- [[04_ARCHITECTURE]] — Tech stack & data flow
- [[05_COMMANDS_AND_FILES]] — Commands & files
- [[06_DEPLOYMENT]] — Deploy process
- [[07_TESTING_AND_VERIFICATION]] — Testing
- [[08_INCIDENTS_AND_FIXES]] — Incidents
- [[09_AGENT_PROMPTS]] — Agent prompts
- [[10_REPORT_INDEX]] — Reports
- [[VAULT_SCHEMA]] — Vault rules
- [[VAULT_CHANGELOG]] — Vault log

## Source Documentation

> Links to original planning docs, design docs, or discussions that informed this project.

- [ ] Link your planning doc here (e.g., [[项目构想]], [[PRD]], [[design-spec]])
EOF
echo "  ✅ 00_HOME.md"

# 01_CURRENT_BASELINE.md
cat > docs/vault/01_CURRENT_BASELINE.md << EOF
---
type: baseline
status: active
confidence: medium
last_updated: $TODAY
owner: agent
reviewed_by: unreviewed
---

# Current Baseline

| Key | Value | Confidence |
|-----|-------|------------|
| **Branch** | $BRANCH | high |
| **HEAD** | $COMMIT_SHORT | high |
| **Phase** | $PHASE | high |
| **Tech** | $TECH_STACK | high |
| **Production** | Not deployed | medium |
| **Tests** | Unknown | low |

## Must NOT Regress

- [ ] Fill in critical features here
EOF
echo "  ✅ 01_CURRENT_BASELINE.md"

# 02_DECISION_LOG.md
cat > docs/vault/02_DECISION_LOG.md << EOF
---
type: decision-log
status: active
confidence: high
last_updated: $TODAY
owner: both
reviewed_by: unreviewed
---

# Decision Log

> Record important decisions here. Newest first.

## Decision: {TITLE}

**Date:** $TODAY | **Status:** Proposed
**Decision:** {What was decided}
**Why:** {Why}
**Do not reverse unless:** {Conditions}
EOF
echo "  ✅ 02_DECISION_LOG.md"

# 03_DO_NOT_TOUCH.md
cat > docs/vault/03_DO_NOT_TOUCH.md << EOF
---
type: danger-zones
status: active
confidence: high
last_updated: $TODAY
owner: human
reviewed_by: human
---

# DO NOT TOUCH

## Files That Must NOT Be Changed Casually

| File | Why | Who Can Change |
|------|-----|---------------|
| {FILE} | {REASON} | {APPROVER} |

## Security Rules

**Never include in any vault file:**
- API keys, tokens, passwords
- Database connection strings
- Internal URLs
- Personal data
EOF

# Add sensitive patterns if detected
if [ -n "$SENSITIVE_PATTERNS" ]; then
  echo "" >> docs/vault/03_DO_NOT_TOUCH.md
  echo "### Detected Sensitive Patterns" >> docs/vault/03_DO_NOT_TOUCH.md
  echo "" >> docs/vault/03_DO_NOT_TOUCH.md
  echo "| Pattern | Source |" >> docs/vault/03_DO_NOT_TOUCH.md
  echo "|---------|--------|" >> docs/vault/03_DO_NOT_TOUCH.md
  echo "$SENSITIVE_PATTERNS" | while read -r pattern; do
    echo "| \`$pattern\` | .env.example |" >> docs/vault/03_DO_NOT_TOUCH.md
  done
fi
echo "  ✅ 03_DO_NOT_TOUCH.md"

# 04_ARCHITECTURE.md
cat > docs/vault/04_ARCHITECTURE.md << EOF
---
type: architecture
status: active
confidence: low
last_updated: $TODAY
owner: agent
reviewed_by: unreviewed
---

# Architecture

## Tech Stack

| Layer | Technology |
|-------|-----------|
| **Stack** | $TECH_STACK |

> Customize this section with your actual architecture.

## Source Documentation

> Link to original design docs or planning documents here.
> This preserves the "why" behind architectural decisions.

- [ ] Link your architecture doc here
EOF
echo "  ✅ 04_ARCHITECTURE.md"

# 05_COMMANDS_AND_FILES.md
cat > docs/vault/05_COMMANDS_AND_FILES.md << EOF
---
type: commands-files
status: active
confidence: medium
last_updated: $TODAY
owner: agent
reviewed_by: unreviewed
---

# Commands and Files

## Commands

### Safe Local

| Command | Purpose | Risk |
|---------|---------|------|
$(echo "$COMMANDS" | head -10 | sed 's/^//' | awk -F' — ' '{printf "| `%s` | %s | 🟢 Safe |\n", $1, $2}')
| \`git status\` | Check changes | 🟢 Safe |

### Deploy

| Command | Purpose | Risk |
|---------|---------|------|
| {DEPLOY_CMD} | Deploy to production | 🔴 Critical |

## File Inventory

| File | Purpose | Risk |
|------|---------|------|
| {FILE} | {PURPOSE} | 🟢/🟡/🟠/🔴 |
EOF
echo "  ✅ 05_COMMANDS_AND_FILES.md"

# 06-10 (minimal templates)
for file_info in \
  "06_DEPLOYMENT.md|deployment|Deployment|Unknown — customize this file" \
  "07_TESTING_AND_VERIFICATION.md|testing|Testing|No automated tests configured" \
  "08_INCIDENTS_AND_FIXES.md|incidents|Incidents|No incidents yet" \
  "09_AGENT_PROMPTS.md|agent-prompts|Agent Prompts|## New Task Startup\n\nRead docs/vault/00_HOME.md before making changes." \
  "10_REPORT_INDEX.md|report-index|Report Index|No reports yet"
do
  IFS='|' read -r fname ftype ftitle fdesc <<< "$file_info"
  cat > "docs/vault/$fname" << EOF
---
type: $ftype
status: active
confidence: low
last_updated: $TODAY
owner: agent
reviewed_by: unreviewed
---

# $ftitle

$fdesc
EOF
  echo "  ✅ $fname"
done

# VAULT_SCHEMA.md
cat > docs/vault/VAULT_SCHEMA.md << EOF
---
type: schema
status: active
confidence: high
last_updated: $TODAY
owner: human
reviewed_by: human
---

# Vault Schema

## Project Identity

**Project:** $PROJECT_NAME
**Phase:** $PHASE

## Vault Version

\`\`\`yaml
vault_version: 5.0.0
vault_created: $TODAY
\`\`\`

## Staleness Thresholds

\`\`\`yaml
staleness_threshold_days: 30
review_threshold_days: 14
audit_interval_days: 30
\`\`\`

## Link Discipline

- 00_HOME is the hub
- Reports only go to 10_REPORT_INDEX
- No circular links
EOF
echo "  ✅ VAULT_SCHEMA.md"

# VAULT_CHANGELOG.md
cat > docs/vault/VAULT_CHANGELOG.md << EOF
---
type: changelog
status: active
confidence: high
last_updated: $TODAY
owner: both
reviewed_by: unreviewed
---

# Vault Changelog

## [$TODAY] init | Vault created

- Phase: $PHASE
- Tech: $TECH_STACK
- Files created: 13
- Auto-generated by init-vault.sh
EOF
echo "  ✅ VAULT_CHANGELOG.md"

# Templates
for tpl in DECISION_TEMPLATE INCIDENT_TEMPLATE DEPLOY_REPORT_TEMPLATE AGENT_TASK_TEMPLATE; do
  touch "docs/vault/templates/$tpl.md"
done
echo "  ✅ Templates created"

# --- Run vault score ---
echo ""
echo "📊 Vault Score:"
TOTAL=13
HIGH_CONF=$(grep -l "confidence: high" docs/vault/*.md 2>/dev/null | wc -l)
HUMAN_REV=$(grep -l "reviewed_by: human" docs/vault/*.md 2>/dev/null | wc -l)

CONF=$((HIGH_CONF * 100 / TOTAL))
FRESH=100
COMP=$((TOTAL * 100 / TOTAL))
REV=$((HUMAN_REV * 100 / TOTAL))
SCORE=$((CONF * 35 / 100 + FRESH * 30 / 100 + COMP * 20 / 100 + REV * 15 / 100))

echo "  Confidence:  $CONF% ($HIGH_CONF/$TOTAL high)"
echo "  Freshness:   100%"
echo "  Completeness: 100%"
echo "  Review:      $REV% ($HUMAN_REV/$TOTAL human)"
echo ""
echo "  VAULT SCORE: $SCORE / 100"

if [ "$SCORE" -ge 90 ]; then echo "  Grade: 🟢 Excellent"
elif [ "$SCORE" -ge 70 ]; then echo "  Grade: 🟡 Good"
elif [ "$SCORE" -ge 50 ]; then echo "  Grade: 🟠 Needs work"
else echo "  Grade: 🔴 Critical"
fi

# --- Git commit ---
echo ""
if git rev-parse --git-dir > /dev/null 2>&1; then
  git add docs/vault/ assets/intake/reports/ .gitignore 2>/dev/null
  git commit -m "docs: create project vault (phase: $PHASE, score: $SCORE)" 2>&1
  echo ""
  echo "✅ Committed to Git"
else
  echo "⚠️  No git repo found. Run 'git init' first."
fi

echo ""
echo "=========================================="
echo "  ✅ Project Vault initialized!"
echo "=========================================="
echo ""
echo "  Next steps:"
echo "  1. Open Obsidian → check Graph View"
echo "  2. Customize docs/vault/00_HOME.md"
echo "  3. Link your planning docs in Source Documentation"
echo "  4. Tell your AI: 'Read docs/vault/00_HOME.md first'"
echo ""
echo "  Connect Obsidian:"
echo "  bash templates/setup-obsidian-link.sh docs/vault \"$PROJECT_NAME\""
echo ""
